# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'
      - name: Install Cypress & Start Node Server
        uses: cypress-io/github-action@v2
        with:
          start: start:npm
          runTests: false
      - name: Run Cypress Test Suite
        uses: cypress-io/github-action@v2
        with:
          installl: false
          browser: chrome
          run: npm run cypress:run