# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches:
      - main

jobs:
  installation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v2
      #
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version:  16 #'16.13.0'
          run: npm --version  
      #
      - name: Install Cypress
        uses: cypress-io/github-action@v2
        with:
         runTests: false
      - run: npm cache clean --force   
  #
  #       
  #
  execute-test-suite-with-chrome:
    runs-on: ubuntu-latest
    needs: [installation]
    steps:
      - name: Execute Cypress Test Suite  With Chrome Browser
        run: npm run cypress:chrome
